<?xml version="1.0"?>
<!DOCTYPE HPCToolkitExperiment [
<!-- ******************************************************************** -->
<!-- HPCToolkit Experiment DTD						  -->
<!-- Version 2.1							  -->
<!-- ******************************************************************** -->
<!ELEMENT HPCToolkitExperiment (Header, (SecCallPathProfile|SecFlatProfile)*)>
<!ATTLIST HPCToolkitExperiment
	  version CDATA #REQUIRED>

  <!-- ****************************************************************** -->

  <!-- Info/NV: flexible name-value pairs: (n)ame; (t)ype; (v)alue -->
  <!ELEMENT Info (NV*)>
  <!ATTLIST Info
	    n CDATA #IMPLIED>
  <!ELEMENT NV EMPTY>
  <!ATTLIST NV
	    n CDATA #REQUIRED
	    t CDATA #IMPLIED
	    v CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Header								  -->
  <!-- ****************************************************************** -->
  <!ELEMENT Header (Info*)>
  <!ATTLIST Header
	    n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section Header							  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecHeader (MetricTable?, MetricDBTable?, TraceDBTable?, LoadModuleTable?, FileTable?, ProcedureTable?, Info*)>

    <!-- MetricTable: -->
    <!ELEMENT MetricTable (Metric)*>

    <!-- Metric: (i)d; (n)ame -->
    <!--   (v)alue-type: transient type of values -->
    <!--   (t)ype: persistent type of metric -->
    <!--   fmt: format; show; -->
    <!ELEMENT Metric (MetricFormula*, Info?)>
    <!ATTLIST Metric
	      i            CDATA #REQUIRED
	      n            CDATA #REQUIRED
	      es	   CDATA #IMPLIED
	      em	   CDATA #IMPLIED
	      ep	   CDATA #IMPLIED
	      v            (raw|final|derived-incr|derived) "raw"
	      t            (inclusive|exclusive|nil) "nil"
	      partner      CDATA #IMPLIED
	      fmt          CDATA #IMPLIED
	      show         (1|0) "1"
	      show-percent (1|0) "1">

    <!-- MetricFormula represents derived metrics: (t)ype; (frm): formula -->
    <!ELEMENT MetricFormula (Info?)>
    <!ATTLIST MetricFormula
	      t   (combine|finalize) "finalize"
	      i   CDATA #IMPLIED
	      frm CDATA #REQUIRED>

    <!-- Metric data, used in sections: (n)ame [from Metric]; (v)alue -->
    <!ELEMENT M EMPTY>
    <!ATTLIST M
	      n CDATA #REQUIRED
	      v CDATA #REQUIRED>

    <!-- MetricDBTable: -->
    <!ELEMENT MetricDBTable (MetricDB)*>

    <!-- MetricDB: (i)d; (n)ame -->
    <!--   (t)ype: persistent type of metric -->
    <!--   db-glob:        file glob describing files in metric db -->
    <!--   db-id:          id within metric db -->
    <!--   db-num-metrics: number of metrics in db -->
    <!--   db-header-sz:   size (in bytes) of a db file header -->
    <!ELEMENT MetricDB EMPTY>
    <!ATTLIST MetricDB
	      i              CDATA #REQUIRED
	      n              CDATA #REQUIRED
	      t              (inclusive|exclusive|nil) "nil"
	      partner        CDATA #IMPLIED
	      db-glob        CDATA #IMPLIED
	      db-id          CDATA #IMPLIED
	      db-num-metrics CDATA #IMPLIED
	      db-header-sz   CDATA #IMPLIED>

    <!-- TraceDBTable: -->
    <!ELEMENT TraceDBTable (TraceDB)>

    <!-- TraceDB: (i)d -->
    <!--   db-min-time: min beginning time stamp (global) -->
    <!--   db-max-time: max ending time stamp (global) -->
    <!ELEMENT TraceDB EMPTY>
    <!ATTLIST TraceDB
	      i            CDATA #REQUIRED
	      db-glob      CDATA #IMPLIED
	      db-min-time  CDATA #IMPLIED
	      db-max-time  CDATA #IMPLIED
	      db-header-sz CDATA #IMPLIED>

    <!-- LoadModuleTable assigns a short name to a load module -->
    <!ELEMENT LoadModuleTable (LoadModule)*>

    <!ELEMENT LoadModule (Info?)>
    <!ATTLIST LoadModule
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- FileTable assigns a short name to a file -->
    <!ELEMENT FileTable (File)*>

    <!ELEMENT File (Info?)>
    <!ATTLIST File
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

    <!-- ProcedureTable assigns a short name to a procedure -->
    <!ELEMENT ProcedureTable (Procedure)*>

    <!ELEMENT Procedure (Info?)>
    <!ATTLIST Procedure
	      i CDATA #REQUIRED
	      n CDATA #REQUIRED>

  <!-- ****************************************************************** -->
  <!-- Section: Call path profile					  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecCallPathProfile (SecHeader, SecCallPathProfileData)>
  <!ATTLIST SecCallPathProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecCallPathProfileData (PF|M)*>
      <!-- Procedure frame -->
      <!--   (i)d: unique identifier for cross referencing -->
      <!--   (s)tatic scope id -->
      <!--   (n)ame: a string or an id in ProcedureTable -->
      <!--   (lm) load module: a string or an id in LoadModuleTable -->
      <!--   (f)ile name: a string or an id in LoadModuleTable -->
      <!--   (l)ine range: "beg-end" (inclusive range) -->
      <!--   (a)lien: whether frame is alien to enclosing P -->
      <!--   (str)uct: hpcstruct node id -->
      <!--   (v)ma-range-set: "{[beg-end), [beg-end)...}" -->
      <!ELEMENT PF (PF|Pr|L|C|S|M)*>
      <!ATTLIST PF
		i  CDATA #IMPLIED
		s  CDATA #IMPLIED
		n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Procedure (static): GOAL: replace with 'P' -->
      <!ELEMENT Pr (Pr|L|C|S|M)*>
      <!ATTLIST Pr
                i  CDATA #IMPLIED
		s  CDATA #IMPLIED
                n  CDATA #REQUIRED
		lm CDATA #IMPLIED
		f  CDATA #IMPLIED
                l  CDATA #IMPLIED
		a  (1|0) "0"
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Callsite (a special StatementRange) -->
      <!ELEMENT C (PF|M)*>
      <!ATTLIST C
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>

  <!-- ****************************************************************** -->
  <!-- Section: Flat profile						  -->
  <!-- ****************************************************************** -->
  <!ELEMENT SecFlatProfile (SecHeader, SecFlatProfileData)>
  <!ATTLIST SecFlatProfile
	    i CDATA #REQUIRED
	    n CDATA #REQUIRED>

    <!ELEMENT SecFlatProfileData (LM|M)*>
      <!-- Load module: (i)d; (n)ame; (v)ma-range-set -->
      <!ELEMENT LM (F|P|M)*>
      <!ATTLIST LM
                i CDATA #IMPLIED
                n CDATA #REQUIRED
		v CDATA #IMPLIED>
      <!-- File -->
      <!ELEMENT F (P|L|S|M)*>
      <!ATTLIST F
                i CDATA #IMPLIED
                n CDATA #REQUIRED>
      <!-- Procedure (Note 1) -->
      <!ELEMENT P (P|A|L|S|C|M)*>
      <!ATTLIST P
                i CDATA #IMPLIED
                n CDATA #REQUIRED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Alien (Note 1) -->
      <!ELEMENT A (A|L|S|C|M)*>
      <!ATTLIST A
                i CDATA #IMPLIED
                f CDATA #IMPLIED
                n CDATA #IMPLIED
                l CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Loop (Note 1,2) -->
      <!ELEMENT L (A|Pr|L|S|C|M)*>
      <!ATTLIST L
		i CDATA #IMPLIED
		s CDATA #IMPLIED
		l CDATA #IMPLIED
	        f CDATA #IMPLIED
		str CDATA #IMPLIED
		v CDATA #IMPLIED>
      <!-- Statement (Note 2) -->
      <!--   (it): trace record identifier -->
      <!ELEMENT S (S|M)*>
      <!ATTLIST S
		i  CDATA #IMPLIED
		it CDATA #IMPLIED
		s  CDATA #IMPLIED
		l  CDATA #IMPLIED
		str  CDATA #IMPLIED
		v  CDATA #IMPLIED>
      <!-- Note 1: Contained Cs may not contain PFs -->
      <!-- Note 2: The 's' attribute is not used for flat profiles -->
]>
<HPCToolkitExperiment version="2.1">
<Header n="kripke">
  <Info/>
</Header>
<SecCallPathProfile i="0" n="kripke">
<SecHeader>
  <MetricTable>
    <Metric i="2" n="CPUTIME (usec):Sum (I)" v="derived-incr" em="0" es="0" ep="-9223372036854775808" t="inclusive" partner="3" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($2, $2)"/>
      <MetricFormula t="finalize" frm="$2"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
    <Metric i="3" n="CPUTIME (usec):Sum (E)" v="derived-incr" em="0" es="0" ep="-9223372036854775808" t="exclusive" partner="2" show="1" show-percent="1">
      <MetricFormula t="combine" frm="sum($3, $3)"/>
      <MetricFormula t="finalize" frm="$3"/>
      <Info><NV n="units" v="events"/></Info>
    </Metric>
  </MetricTable>
  <MetricDBTable>
    <MetricDB i="0" n="CPUTIME (usec) (I)" t="inclusive" partner="1" db-glob="*.metric-db" db-id="0" db-num-metrics="2" db-header-sz="24"/>
    <MetricDB i="1" n="CPUTIME (usec) (E)" t="exclusive" partner="0" db-glob="*.metric-db" db-id="1" db-num-metrics="2" db-header-sz="24"/>
  </MetricDBTable>
  <LoadModuleTable>
    <LoadModule i="2" n="/g/g92/bhatele1/llnl/hpctoolkit/Kripke/build-mvapich2.3/kripke"/>
    <LoadModule i="1376" n="&lt;unknown load module&gt;"/>
    <LoadModule i="1382" n="/collab/usr/global/tools/hpctoolkit/toss_3_x86_64_ib/2019-02-26/packages/linux-rhel7-x86_64/gcc-4.9.3/hpctoolkit-develop-szfcj5uplk66ruwembpihb7kexoonoti/lib/hpctoolkit/ext-libs/libmonitor.so.0.0.0"/>
    <LoadModule i="1400" n="/usr/tce/packages/mvapich2/mvapich2-2.3-intel-18.0.1/lib/libmpi.so.12.1.1"/>
    <LoadModule i="2079" n="/usr/tce/packages/gcc/gcc-4.9.3/lib64/libstdc++.so.6.0.20"/>
    <LoadModule i="2141" n="/usr/lib64/libc-2.17.so"/>
    <LoadModule i="2564" n="/usr/lib64/libpthread-2.17.so"/>
    <LoadModule i="2580" n="/usr/lib64/librt-2.17.so"/>
    <LoadModule i="2584" n="/usr/lib64/ld-2.17.so"/>
    <LoadModule i="2637" n="/usr/lib64/libpsm2.so.2.1"/>
    <LoadModule i="5051" n="/usr/lib64/libpmi2.so.0.0.0"/>
    <LoadModule i="5075" n="/usr/tce/packages/intel/intel-18.0.1/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin/libintlc.so.5"/>
  </LoadModuleTable>
  <FileTable>
    <File i="3" n="&lt;unknown file&gt; [kripke]"/>
    <File i="1377" n="&lt;unknown file&gt;"/>
    <File i="1383" n="&lt;unknown file&gt; [libmonitor.so.0.0.0]"/>
    <File i="1401" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/init/init.c"/>
    <File i="1404" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/init/initthread.c"/>
    <File i="1407" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_init.c"/>
    <File i="1410" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_entry.c"/>
    <File i="1413" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/timer/wtime.c"/>
    <File i="1416" n="/builddir/build/BUILD/mvapich2-2.3/src/openpa/src/primitives/opa_gcc_intel_32_64_ops.h"/>
    <File i="1421" n="&lt;unknown file&gt; [libmpi.so.12.1.1]"/>
    <File i="1426" n="/builddir/build/BUILD/mvapich2-2.3/src/util/timers/mpiu_timer.c"/>
    <File i="1435" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/comm_size.c"/>
    <File i="1440" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/comm_rank.c"/>
    <File i="1445" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/irecv.c"/>
    <File i="1454" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_irecv.c"/>
    <File i="1459" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/ch3u_request.c"/>
    <File i="1465" n="/builddir/build/BUILD/mvapich2-2.3/src/util/mem/handlemem.c"/>
    <File i="1497" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/mpidi_calls.c"/>
    <File i="1500" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_recv.c"/>
    <File i="1504" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_queue.c"/>
    <File i="1517" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/waitall.c"/>
    <File i="1563" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/mpir_request.c"/>
    <File i="1568" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/debugger/dbginit.c"/>
    <File i="1588" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/testany.c"/>
    <File i="1674" n="/builddir/build/BUILD/mvapich2-2.3/./src/include/mpiimpl.h"/>
    <File i="1693" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/pt2pt/isend.c"/>
    <File i="1705" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_isend.c"/>
    <File i="1718" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/ch3u_eager.c"/>
    <File i="1727" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_istart.c"/>
    <File i="1733" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/channels/psm/src/psm_send.c"/>
    <File i="1743" n="/builddir/build/BUILD/mvapich2-2.3/src/pmi/upmi/upmi.c"/>
    <File i="1757" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/reduce.c"/>
    <File i="1762" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/opsum.c"/>
    <File i="1771" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/reduce_osu.c"/>
    <File i="1799" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/helper_fns.c"/>
    <File i="1805" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_recv.c"/>
    <File i="1822" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_send.c"/>
    <File i="1840" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/ch3_shmem_coll.c"/>
    <File i="1865" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/comm_test_inter.c"/>
    <File i="1870" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/create_2level_comm.c"/>
    <File i="1873" n="./src/usr/include/pthread.h"/>
    <File i="1885" n="/builddir/build/BUILD/mvapich2-2.3/src/mpid/ch3/src/mpid_vc.c"/>
    <File i="1892" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/allreduce.c"/>
    <File i="1895" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/allreduce_osu.c"/>
    <File i="1912" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/opland.c"/>
    <File i="1924" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/allgather.c"/>
    <File i="1928" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/allgather_osu.c"/>
    <File i="1938" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/comm_group.c"/>
    <File i="1944" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/group/grouputil.c"/>
    <File i="1960" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/group/group_incl.c"/>
    <File i="1968" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/comm_create.c"/>
    <File i="1974" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/comm/contextid.c"/>
    <File i="1978" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/opband.c"/>
    <File i="2007" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/bcast.c"/>
    <File i="2010" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/bcast_osu.c"/>
    <File i="2030" n="./src/usr/include/sys/stat.h"/>
    <File i="2048" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/barrier.c"/>
    <File i="2055" n="/builddir/build/BUILD/mvapich2-2.3/src/mpi/coll/barrier_osu.c"/>
    <File i="2080" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.tcc"/>
    <File i="2083" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/char_traits.h"/>
    <File i="2086" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/bits/basic_string.h"/>
    <File i="2092" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/ext/new_allocator.h"/>
    <File i="2095" n="/builddir/build/BUILD/gccspack/spack/var/spack/stage/gcc-4.9.3-34vmmvov5ct2riknhkfcmxieffb5pyex/gcc-4.9.3/libstdc++-v3/libsupc++/new_op.cc"/>
    <File i="2103" n="&lt;unknown file&gt; [libstdc++.so.6.0.20]"/>
    <File i="2117" n="/builddir/build/BUILD/gccspack/spack/var/spack/stage/gcc-4.9.3-34vmmvov5ct2riknhkfcmxieffb5pyex/gcc-4.9.3/libstdc++-v3/src/c++98/tree.cc"/>
    <File i="2121" n="/tmp/mockbuild/spack-stage/spack-stage-P3jF0z/spack-build/x86_64-unknown-linux-gnu/libstdc++-v3/include/ext/atomicity.h"/>
    <File i="2128" n="/builddir/build/BUILD/gccspack/spack/var/spack/stage/gcc-4.9.3-34vmmvov5ct2riknhkfcmxieffb5pyex/gcc-4.9.3/libstdc++-v3/libsupc++/del_op.cc"/>
    <File i="2142" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/multiarch/strlen-sse2-pminub.S"/>
    <File i="2145" n="./src/usr/src/debug/glibc-2.17-c758a686/malloc/malloc.c"/>
    <File i="2152" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/multiarch/memcpy-ssse3-back.S"/>
    <File i="2155" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/memset.S"/>
    <File i="2167" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/clock_gettime.c"/>
    <File i="2171" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/multiarch/memcmp-sse4.S"/>
    <File i="2234" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/sysv/linux/wordsize-64/mmap.c"/>
    <File i="2241" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/syscall-template.S"/>
    <File i="2256" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/sysv/linux/writev.c"/>
    <File i="2261" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/sysdeps/unix/sysv/linux/x86_64/cancellation.S"/>
    <File i="2345" n="./src/usr/src/debug/glibc-2.17-c758a686/debug/snprintf_chk.c"/>
    <File i="2348" n="./src/usr/src/debug/glibc-2.17-c758a686/debug/vsnprintf_chk.c"/>
    <File i="2351" n="./src/usr/src/debug/glibc-2.17-c758a686/libio/genops.c"/>
    <File i="2367" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/sysv/linux/wordsize-64/fxstat.c"/>
    <File i="2371" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/vfprintf.c"/>
    <File i="2374" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/_itoa.c"/>
    <File i="2491" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/snprintf.c"/>
    <File i="2494" n="./src/usr/src/debug/glibc-2.17-c758a686/libio/vsnprintf.c"/>
    <File i="2497" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/printf-parse.h"/>
    <File i="2500" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/strchrnul.S"/>
    <File i="2504" n="./src/usr/src/debug/glibc-2.17-c758a686/libio/strops.c"/>
    <File i="2511" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/isoc99_sscanf.c"/>
    <File i="2514" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/isoc99_vsscanf.c"/>
    <File i="2517" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/vfscanf.c"/>
    <File i="2523" n="./src/usr/src/debug/glibc-2.17-c758a686/stdio-common/sscanf.c"/>
    <File i="2526" n="./src/usr/src/debug/glibc-2.17-c758a686/libio/iovsscanf.c"/>
    <File i="2530" n="./src/usr/src/debug/glibc-2.17-c758a686/stdlib/strtol_l.c"/>
    <File i="2533" n="./src/usr/src/debug/glibc-2.17-c758a686/stdlib/getenv.c"/>
    <File i="2542" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/sysv/linux/x86_64/sigaction.c"/>
    <File i="2546" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/strlen.S"/>
    <File i="2551" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/forward.c"/>
    <File i="2557" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/sysv/linux/usleep.c"/>
    <File i="2565" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/sysdeps/x86_64/pthread_spin_lock.S"/>
    <File i="2568" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/sysdeps/x86_64/pthread_spin_unlock.S"/>
    <File i="2574" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/cleanup_defer_compat.c"/>
    <File i="2577" n="./src/usr/src/debug/glibc-2.17-c758a686/nptl/pthread_mutex_lock.c"/>
    <File i="2581" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/unix/sysv/linux/shm_open.c"/>
    <File i="2585" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/dl-trampoline.h"/>
    <File i="2588" n="./src/usr/src/debug/glibc-2.17-c758a686/elf/dl-runtime.c"/>
    <File i="2593" n="./src/usr/src/debug/glibc-2.17-c758a686/elf/dl-lookup.c"/>
    <File i="2603" n="./src/usr/src/debug/glibc-2.17-c758a686/elf/dl-misc.c"/>
    <File i="2612" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/x86_64/strcmp.S"/>
    <File i="2634" n="./src/usr/src/debug/glibc-2.17-c758a686/sysdeps/generic/dl-hash.h"/>
    <File i="2638" n="&lt;unknown file&gt; [libpsm2.so.2.1]"/>
    <File i="5052" n="/builddir/build/BUILD/slurm-17.11.12-1.3.1.ch6/contribs/pmi2/pmi2_api.c"/>
    <File i="5058" n="./src/usr/include/bits/stdio2.h"/>
    <File i="5064" n="./src/usr/include/bits/unistd.h"/>
    <File i="5076" n="&lt;unknown file&gt; [libintlc.so.5]"/>
  </FileTable>
  <ProcedureTable>
    <Procedure i="30" n="memcmp@plt"/>
    <Procedure i="38" n="memset@plt"/>
    <Procedure i="40" n="std::basic_string&lt;char, std::char_traits&lt;char&gt;, std::allocator&lt;char&gt; &gt;::basic_string(std::string const&amp;)@plt"/>
    <Procedure i="58" n="std::string::_Rep::_M_destroy(std::allocator&lt;char&gt; const&amp;)@plt"/>
    <Procedure i="66" n="operator delete(void*)@plt"/>
    <Procedure i="70" n="operator new(unsigned long)@plt"/>
    <Procedure i="86" n="MPI_Comm_size@plt"/>
    <Procedure i="94" n="MPI_Wtime@plt"/>
    <Procedure i="102" n="MPI_Irecv@plt"/>
    <Procedure i="104" n="MPI_Testany@plt"/>
    <Procedure i="112" n="MPI_Comm_rank@plt"/>
    <Procedure i="128" n="memmove@plt"/>
    <Procedure i="158" n="main"/>
    <Procedure i="260" n="Grid_Data::particleEdit"/>
    <Procedure i="590" n="std::vector&lt;int, std::allocator&lt;int&gt; &gt;::_M_insert_aux"/>
    <Procedure i="592" n="SweepSubdomains"/>
    <Procedure i="598" n="SweepSolver"/>
    <Procedure i="632" n="Timing::start"/>
    <Procedure i="636" n="Timing::stop"/>
    <Procedure i="704" n="std::_Rb_tree&lt;std::string, std::pair&lt;std::string const, Timer&gt;, std::_Select1st&lt;std::pair&lt;std::string const, Timer&gt; &gt;, std::less&lt;std::string&gt;, std::allocator&lt;std::pair&lt;std::string const, Timer&gt; &gt; &gt;::_M_insert_unique_"/>
    <Procedure i="814" n="Kernel_3d_DGZ::LTimes"/>
    <Procedure i="828" n="Kernel_3d_DGZ::LPlusTimes"/>
    <Procedure i="840" n="Kernel_3d_DGZ::scattering"/>
    <Procedure i="854" n="Kernel_3d_DGZ::source"/>
    <Procedure i="862" n="Kernel_3d_DGZ::sweep"/>
    <Procedure i="1204" n="SweepComm::~SweepComm"/>
    <Procedure i="1206" n="SweepComm::addSubdomain"/>
    <Procedure i="1208" n="SweepComm::readySubdomains"/>
    <Procedure i="1210" n="SweepComm::markComplete"/>
    <Procedure i="1212" n="SweepComm::SweepComm"/>
    <Procedure i="1214" n="SweepComm::workRemaining"/>
    <Procedure i="1310" n="ParallelComm::workRemaining"/>
    <Procedure i="1312" n="ParallelComm::ParallelComm"/>
    <Procedure i="1314" n="ParallelComm::~ParallelComm"/>
    <Procedure i="1326" n="ParallelComm::dequeueSubdomain"/>
    <Procedure i="1330" n="ParallelComm::waitAllSends"/>
    <Procedure i="1334" n="ParallelComm::testRecieves"/>
    <Procedure i="1342" n="ParallelComm::postSends"/>
    <Procedure i="1358" n="ParallelComm::getReadyList"/>
    <Procedure i="1362" n="ParallelComm::postRecvs"/>
    <Procedure i="1366" n="std::vector&lt;Subdomain*, std::allocator&lt;Subdomain*&gt; &gt;::_M_insert_aux"/>
    <Procedure i="1378" n="&lt;partial call paths&gt;" f="1"/>
    <Procedure i="1380" n="&lt;unknown procedure&gt;"/>
    <Procedure i="1384" n="&lt;program root&gt;" f="1"/>
    <Procedure i="1386" n="MPI_Init"/>
    <Procedure i="1388" n="pthread_create"/>
    <Procedure i="1390" n="MPI_Comm_rank"/>
    <Procedure i="1392" n="monitor_set_mpi_size_rank"/>
    <Procedure i="1394" n="&lt;unknown procedure&gt; 0x3460 [libmonitor.so.0.0.0]"/>
    <Procedure i="1396" n="monitor_appl_sigaction"/>
    <Procedure i="1398" n="monitor_remove_client_signals"/>
    <Procedure i="1402" n="PMPI_Init"/>
    <Procedure i="1405" n="MPIR_Init_thread"/>
    <Procedure i="1408" n="MPID_Init"/>
    <Procedure i="1411" n="psm_doinit"/>
    <Procedure i="1740" n="psm_connect_peer"/>
    <Procedure i="1414" n="PMPI_Wtime"/>
    <Procedure i="1417" n="OPA_load_int"/>
    <Procedure i="1422" n="&lt;unknown procedure&gt; 0x142440 [libmpi.so.12.1.1]"/>
    <Procedure i="1424" n="&lt;unknown procedure&gt; 0x143150 [libmpi.so.12.1.1]"/>
    <Procedure i="1430" n="&lt;unknown procedure&gt; 0x140050 [libmpi.so.12.1.1]"/>
    <Procedure i="1452" n="&lt;unknown procedure&gt; 0x144370 [libmpi.so.12.1.1]"/>
    <Procedure i="1463" n="&lt;unknown procedure&gt; 0x142210 [libmpi.so.12.1.1]"/>
    <Procedure i="1493" n="&lt;unknown procedure&gt; 0x1402b0 [libmpi.so.12.1.1]"/>
    <Procedure i="1495" n="&lt;unknown procedure&gt; 0x140dc0 [libmpi.so.12.1.1]"/>
    <Procedure i="1509" n="&lt;unknown procedure&gt; 0x140620 [libmpi.so.12.1.1]"/>
    <Procedure i="1545" n="&lt;unknown procedure&gt; 0x13f5a0 [libmpi.so.12.1.1]"/>
    <Procedure i="1550" n="&lt;unknown procedure&gt; 0x145420 [libmpi.so.12.1.1]"/>
    <Procedure i="1607" n="&lt;unknown procedure&gt; 0x143100 [libmpi.so.12.1.1]"/>
    <Procedure i="1611" n="&lt;unknown procedure&gt; 0x140b40 [libmpi.so.12.1.1]"/>
    <Procedure i="1626" n="&lt;unknown procedure&gt; 0x142f30 [libmpi.so.12.1.1]"/>
    <Procedure i="1628" n="&lt;unknown procedure&gt; 0x144b30 [libmpi.so.12.1.1]"/>
    <Procedure i="1634" n="&lt;unknown procedure&gt; 0x1447d0 [libmpi.so.12.1.1]"/>
    <Procedure i="1649" n="&lt;unknown procedure&gt; 0x140570 [libmpi.so.12.1.1]"/>
    <Procedure i="1671" n="&lt;unknown procedure&gt; 0x142d70 [libmpi.so.12.1.1]"/>
    <Procedure i="1683" n="&lt;unknown procedure&gt; 0x142a90 [libmpi.so.12.1.1]"/>
    <Procedure i="1703" n="&lt;unknown procedure&gt; 0x141110 [libmpi.so.12.1.1]"/>
    <Procedure i="1776" n="&lt;unknown procedure&gt; 0x143cb0 [libmpi.so.12.1.1]"/>
    <Procedure i="1785" n="log2"/>
    <Procedure i="1787" n="__libm_log2_l9"/>
    <Procedure i="1789" n="__libm_exp2_l9"/>
    <Procedure i="1797" n="&lt;unknown procedure&gt; 0x142db0 [libmpi.so.12.1.1]"/>
    <Procedure i="1883" n="&lt;unknown procedure&gt; 0x143080 [libmpi.so.12.1.1]"/>
    <Procedure i="1916" n="log2f"/>
    <Procedure i="1995" n="&lt;unknown procedure&gt; 0x144fb0 [libmpi.so.12.1.1]"/>
    <Procedure i="2062" n="&lt;unknown procedure&gt; 0x140980 [libmpi.so.12.1.1]"/>
    <Procedure i="2070" n="&lt;unknown procedure&gt; 0x141860 [libmpi.so.12.1.1]"/>
    <Procedure i="1427" n="MPIU_Wtime"/>
    <Procedure i="1432" n="MPIU_Wtime_todouble"/>
    <Procedure i="1436" n="PMPI_Comm_size"/>
    <Procedure i="1441" n="PMPI_Comm_rank"/>
    <Procedure i="1446" n="PMPI_Irecv"/>
    <Procedure i="1455" n="MPID_Irecv"/>
    <Procedure i="1460" n="MPID_Request_create"/>
    <Procedure i="1577" n="MPIDI_CH3_Request_destroy"/>
    <Procedure i="1651" n="MPID_Request_release"/>
    <Procedure i="1948" n="MPIU_Handle_direct_init"/>
    <Procedure i="1473" n="MPIU_Handle_indirect_init"/>
    <Procedure i="1466" n="MPIU_Handle_obj_alloc"/>
    <Procedure i="1468" n="MPIU_Handle_obj_alloc_unsafe"/>
    <Procedure i="1575" n="MPIU_Handle_obj_free"/>
    <Procedure i="1525" n="MPIU_Handle_get_ptr_indirect"/>
    <Procedure i="1725" n="MPIDI_CH3_iSendv"/>
    <Procedure i="1530" n="MPIDI_CH3_Progress_start"/>
    <Procedure i="1534" n="MPIDI_CH3_Progress_wait"/>
    <Procedure i="1630" n="MPIDI_CH3_Progress_test"/>
    <Procedure i="1498" n="MPIDI_CH3_iRecv"/>
    <Procedure i="1808" n="psm_recv"/>
    <Procedure i="1501" n="psm_irecv"/>
    <Procedure i="1555" n="psm_complete_req"/>
    <Procedure i="1552" n="psm_process_completion"/>
    <Procedure i="1811" n="psm_try_complete"/>
    <Procedure i="1536" n="psm_progress_wait"/>
    <Procedure i="1580" n="psm_dequeue_compreq"/>
    <Procedure i="1505" n="psm_no_lock"/>
    <Procedure i="1560" n="psm_update_mpistatus"/>
    <Procedure i="1522" n="MPIR_Waitall_impl"/>
    <Procedure i="1518" n="PMPI_Waitall"/>
    <Procedure i="1564" n="MPIR_Request_complete"/>
    <Procedure i="1750" n="MPIR_Sendq_remember"/>
    <Procedure i="1569" n="MPIR_Sendq_forget"/>
    <Procedure i="1589" n="PMPI_Testany"/>
    <Procedure i="1675" n="MPIR_Comm_release"/>
    <Procedure i="1694" n="PMPI_Isend"/>
    <Procedure i="1706" n="MPID_Isend"/>
    <Procedure i="1826" n="MPIDI_CH3_EagerContigSend"/>
    <Procedure i="1719" n="MPIDI_CH3_EagerContigIsend"/>
    <Procedure i="1828" n="psm_istartmsgv"/>
    <Procedure i="1728" n="psm_isendv"/>
    <Procedure i="1830" n="psm_send_pkt"/>
    <Procedure i="1734" n="psm_isend_pkt"/>
    <Procedure i="1814" n="psm_create_req"/>
    <Procedure i="1744" n="UPMI_KVS_GET"/>
    <Procedure i="1767" n="MPIR_Reduce_impl"/>
    <Procedure i="1758" n="PMPI_Reduce"/>
    <Procedure i="1763" n="MPIR_SUM_check_dtype"/>
    <Procedure i="1792" n="MPIR_Reduce_binomial_MV2"/>
    <Procedure i="1837" n="MPIR_Reduce_shmem_MV2"/>
    <Procedure i="1835" n="MPIR_Reduce_two_level_helper_MV2"/>
    <Procedure i="1778" n="MPIR_Reduce_index_tuned_intra_MV2"/>
    <Procedure i="1772" n="MPIR_Reduce_MV2"/>
    <Procedure i="1800" n="MPIR_Localcopy"/>
    <Procedure i="1907" n="MPIC_Wait"/>
    <Procedure i="1820" n="MPIC_Send"/>
    <Procedure i="1803" n="MPIC_Recv"/>
    <Procedure i="1903" n="MPIC_Sendrecv"/>
    <Procedure i="1806" n="MPID_Recv"/>
    <Procedure i="1823" n="MPID_Send"/>
    <Procedure i="1841" n="MPIDI_CH3I_SHMEM_COLL_GetShmemBuf"/>
    <Procedure i="1854" n="MPIDI_CH3I_SHMEM_COLL_SetGatherComplete"/>
    <Procedure i="2072" n="MPIDI_CH3I_SHMEM_COLL_Barrier_bcast"/>
    <Procedure i="1862" n="mv2_increment_shmem_coll_counter"/>
    <Procedure i="2039" n="mv2_shm_progress"/>
    <Procedure i="2037" n="mv2_shm_barrier"/>
    <Procedure i="2028" n="mv2_shm_coll_init"/>
    <Procedure i="1866" n="PMPI_Comm_test_inter"/>
    <Procedure i="1880" n="create_2level_comm"/>
    <Procedure i="1871" n="check_split_comm"/>
    <Procedure i="1874" n="pthread_equal"/>
    <Procedure i="1953" n="MPID_Comm_get_lpid"/>
    <Procedure i="1886" n="MPID_Get_node_id"/>
    <Procedure i="1893" n="MPIR_Allreduce_impl"/>
    <Procedure i="1901" n="MPIR_Allreduce_pt2pt_rd_MV2"/>
    <Procedure i="1898" n="MPIR_Allreduce_index_tuned_intra_MV2"/>